### ISSUE TITLE
Consider upgrade this task to the latest Node

### ISSUE THREAD

**Issue by mskyongk** [shayki5/azure-devops-print-all-variables#16]
In my environment, Node 6 will not be allowed near future.
"Task 'Print all variables' version 1 (printAllVariables@1) is dependent on a Node version (6) that is end-of-life. "

Can you please consider upgrading this task to the latest Node?
https://learn.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops#q-how-can-i-upgrade-my-custom-task-to-the-latest-node

Thanks

**Comment by shayki5** [comment]
Done :) #17

**Comment by mskyongk** [comment]
Thanks so much for addressing it quickly!
