### ISSUE TITLE
Upgrade to Node 10 execution handler

### ISSUE THREAD

**Issue by MarcMei80** [shayki5/azure-devops-print-all-variables#6]
**Are you reporting a bug or a feature request ?**

- [ ] Bug
- [x] Feature Request

**Description**
Azure is giving this warning:

_[warning]This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration._

See https://aka.ms/migrateTaskNode10

**Reproduction**

`- task: printAllVariables@1`

**System Information**

Current agent version: '2.195.0'
Operating System
Ubuntu
20.04.3
LTS
Virtual Environment
Environment: ubuntu-20.04
Version: 20211114.1
Virtual Environment Provisioner
1.0.0.0-master-20211117-1
Current image version: '20211114.1'
Agent running as: 'vsts'

**Comment by shayki5** [comment]
Upgraded to Node16 :)
#17
